name: release-singbox-rule

on: push

jobs:
    build:
        runs-on: ubuntu-latest

        steps: 
            - name: checkout
              uses: actions/checkout@v4
            
            - name: setup-python
              uses: actions/setup-python@v3
              with:
                python-version: "3.10"

            - name: install-py-dependencies
              run: |
                python -m pip install --upgrade pip
                if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

            - name: setup-sing-box
              run: |
                bash <(curl -fsSL https://sing-box.app/deb-install.sh)

            - name: compile-rulesets
              run: |
                python convert.py

            - name: release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                files: ./output/*
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Clean old release and tag
              uses: dev-drprasad/delete-older-releases@v0.3.2
              with:
                keep_latest: 5
                delete_tags: true
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
